### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by rzumer** [JWSoh/ARTN#1]
Hello,
As you mentioned that you would add more content to this repository following review, and it is now published by IEEE, are you able to release training and inference code for ARTN?

**Comment by JWSoh** [comment]
We apologize for the late response. We just updated the test codes and the models. For the training, you just need to slightly modify deploy prototxt and create solver.

**Comment by JWSoh** [comment]
> Hello,
> As you mentioned that you would add more content to this repository following review, and it is now published by IEEE, are you able to release training and inference code for ARTN?

We apologize for the late response. We just updated the test codes and the models. For the training, you just need to slightly modify deploy prototxt and create solver.

**Comment by rzumer** [comment]
Thank you.
